// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIE1hJJeb2qOmCbFLj-S6FCpLbxnPjkqE',
    appId: '1:401468010364:android:b08d516bfcf7092358bef9',
    messagingSenderId: '401468010364',
    projectId: 'my-nady',
    storageBucket: 'my-nady.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi0VDYeLzSwFmjeriPOPWEcVIVNw7Sa0c',
    appId: '1:401468010364:ios:e121dbfc1d83c42758bef9',
    messagingSenderId: '401468010364',
    projectId: 'my-nady',
    storageBucket: 'my-nady.firebasestorage.app',
    iosBundleId: 'com.example.myNadyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY_fGkl0BmzzIMUsJSh1mCPGdqjjNQ_sE',
    appId: '1:401468010364:web:7a78557fe0ad2f5958bef9',
    messagingSenderId: '401468010364',
    projectId: 'my-nady',
    authDomain: 'my-nady.firebaseapp.com',
    storageBucket: 'my-nady.firebasestorage.app',
    measurementId: 'G-SHFDJGYVC4',
  );
}
